version: "3"
services:

  vocables:
    restart: unless-stopped
    image: souslesens/souslesensvocables:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${VOCABLES_LISTEN_PORT:-3010}:3010"
    volumes:
      - "${DATA_ROOT_DIR:-/tmp}/vocables/app/config:\
      /app/config"
    env_file:
      - default.env
      - .env
    networks:
      - backend

  virtuoso:
    image: askomics/virtuoso:7.2.5.1
    ports:
      - ${VIRTUOSO_LISTEN_PORT:-8890}:8890
    volumes:
      - "${DATA_ROOT_DIR:-/tmp}/vocables/virtuoso/data:\
        /data"
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
